[build]
publish = "build/"
command = "npm run build"

[[redirects]]
from = "https://tjonesdev.netlify.app"
to = "https://www.tjonesdev.com"
status = 301
force = true

[[redirects]]
from = "https://calculator.tjonesdev.com"
to = "https://www.tjonesdev.com/calculator"
status = 301
force = true